### ISSUE TITLE
 Catalog of my things

### ISSUE THREAD

**Issue by Tafloninno** [zeff96/catalog_of_my_things#26]
[ Catalog of my things Project](https://github.com/users/zeff96/projects/7)

The team comprises 3 team members

Team member 1 - @c00p75 
Team member 2 - @Tafloninno 
Team member 3 - @zeff96

**Comment by joel-kalema** [comment]
Hi Team

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 

- [x] You have submitted a project that doesn't have a link to the project 😢, it supposes to have this [link](https://github.com/users/zeff96/projects/7/views/1) 👍 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @joel-kalema in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by muneebulrehman** [comment]
Hi team, 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Great job distributing the tasks fairly.

## Required Changes ♻️
_Check the comments under the review._

One particular task for **Team member #2** is missing from your board. This particular one. ⬇️. Kindly add it and then submit it for a re-review.
![image](https://github.com/zeff96/catalog_of_my_things/assets/33268927/d734a92a-4bfe-4a26-99c5-17b1c2098472)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
> [ Catalog of my things Project](https://github.com/users/zeff96/projects/7)
> 
> The team comprises 3 team members
> 
> Team member 1 - @c00p75 Team member 2 - @Tafloninno Team member 3 - @zeff96

Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/3oz8xAFtqoOUUrsh7W/giphy.gif"/>
## Highlights
- Requested task added ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
